version: '3'
services:
  backend:
    image: sva4rd/calculator-backend:latest
    ports:
      - "8080:8080"
    networks:
      - app-network
  frontend:
    build: .
    image: sva4rd/calculator-frontend:latest
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
